FROM node:20 as build


RUN yarn global add typescript

WORKDIR /app
COPY . .

RUN yarn install --production
RUN yarn build:prod


FROM nginx:1.23.3 as prod
EXPOSE 80

COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d


CMD [ "nginx", "-g","daemon off;"]